---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-atlas-osb  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-atlas-osb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mongodb-atlas-osb
    namespace: default 
  - kind: ServiceAccount
    name: mongodb-atlas-osb
    namespace: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-atlas-osb-configuration
data:
  ATLAS_GROUP_ID: 'XXX'
  ATLAS_BASE_URL: 'https://cloud.mongodb.com'
  BROKER_HOST: '127.0.0.1'
  BROKER_PORT: '4000'
  BROKER_LOG_LEVEL: 'INFO' # DEBUG, INFO, WARN, ERROR
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-osb-credentials
type: Opaque
stringData:
  ATLAS_PUBLIC_KEY: 'XXX'
  ATLAS_PRIVATE_KEY: 'XXX'
  BROKER_USERNAME: 'atlas'
  BROKER_PASSWORD: 'secret123'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-atlas-osb
  name: mongodb-atlas-osb
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80
    name: http 
  selector:
    app: mongodb-atlas-osb 
  type: LoadBalancer
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: mongodb-atlas-osb
spec:
  authInfo:
    basic:
      secretRef:
        name: mongodb-atlas-osb-credentials
        namespace: mongodb
  url: http://mongodb-atlas-osb.mongodb.svc.cluster.local 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "mongodb-atlas-osb"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: "mongodb-atlas-osb"
    spec:
      serviceAccountName: "mongodb-atlas-osb"
      containers:
      - name: "mongodb-atlas-osb"
        image: "jmimick/mongodb-atlas-service-broker:latest"
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 80 
        envFrom:
        - configMapRef:
            name: mongodb-atlas-osb-configuration
        - secretRef:
            name: mongodb-atlas-osb-credentials
