---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-charts-{{ name }}  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "mongodb-charts-{{ name }}-configuration"
data:
  broker.yaml: |-
    testing: 123
    foobar: "I can't drive 55."
---
apiVersion: v1
kind: Secret
metadata:
  name: "mongodb-charts-{{ name }}-credentials"
stringData:
  username: "charts"
  password: "charts"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-charts-{{ name }}
  name: mongodb-charts-{{ name }}
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80
    name: http 
  selector:
    app: mongodb-charts-{{ name }} 
  type: LoadBalancer
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: mongodb-charts-{{ name }}
spec:
  authInfo:
    basic:
      secretRef:
        name: mongodb-charts-{{ name }}-credentials
        namespace: mongodb
  url: http://mongodb-charts-{{ name }}.mongodb.svc.cluster.local:5000 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "mongodb-charts-{{ name }}"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: "mongodb-charts-{{ name }}"
    spec:
      serviceAccountName: "mongodb-charts-{{ name }}"
      containers:
      - name: "mongodb-charts-{{ name }}"
        image: quay.io/mongodb/charts:19.06.1
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 80 
        - name: https
          containerPort: 443 
        env:
        - name: CHARTS_SUPPORT_WIDGET_AND_METRICS
          value: on
        - name: SSL_CERT_DIR
          value: /mongodb-charts/volumes/db-certs
        #- name: CHARTS_HTTPS_CERTIFICATE_FILE
        #  value: charts-https.crt
        #- name: CHARTS_HTTPS_CERTIFICATE_KEY_FILE
        #  value: charts-https.key

        volumeMounts:
        - name: keys
          mountPath: /mongodb-charts/volumes/keys
          readOnly: true
        - name: logs
          mountPath: /mongodb-charts/volumes/logs
          readOnly: true
        - name: web-certs
          mountPath: /mongodb-charts/volumes/web-certs
          readOnly: true
        - name: db-certs
          mountPath: /mongodb-charts/volumes/db-certs
          readOnly: true
      volumes:
      - name: mongodb-charts-{{ name }}-configuration
        configMap:
          name: mongodb-charts-{{ name }}-configuration
      - name: charts-mongodb-uri
        secret:
          secretName: charts-mongodb-uri
      - name: mongodb-charts-{{ name }}-credentials
        secret:
          secretName: mongodb-charts-{{ name }}-credentials
